/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import calculadora.Calculadora;

public class App
{
    Calculadora c;

    public static void main(String[] args)
    {
        Calculadora c = new Calculadora();
        ejecutando(c);
    }

    private static void ejecutando(Calculadora c)
    {
        System.out.println("Calculadora aritmetica (3.0)");
        System.out.println("=============================");
        System.out.println("suma                2+3= " + c.suma(2, 3));
        System.out.println("suma            1.3+2.3= " + fijarNumero(c.suma(1.3, 2.3),1));
        System.out.println("resta               2-3=" + c.resta(2, 3));
        System.out.println("resta           2.2-2.4=" + fijarNumero(c.resta(2.2, 2.4),1));
        System.out.println("multiplicación      2*3= " + c.multiplica(2, 3));
        System.out.println("multiplicación  2.4*4.5= " + fijarNumero(c.multiplica(2.4, 4.5),1));
        System.out.println("división           12/4= " + c.divide(12, 4));
        System.out.println("división            2/0= " + c.divideCero(2, 0));
        System.out.println("seno de 30,     sin(30)= " +fijarNumero(c.seno(30),1));
        System.out.println("coseno de 90,   cos(90)= " +fijarNumero(c.coseno(90),1));
        System.out.println("tangente de 45, tan(45)= " +fijarNumero(c.tangente(45),1));
        
        System.out.println("\nAutor: Ricardo Rafael Quintero Meza-ITC");
    }  
    public static double fijarNumero(double numero, int digitos)
    {
        double resultado;
        resultado = numero * Math.pow(10, digitos);
        resultado = Math.round(resultado);
        resultado = resultado/Math.pow(10, digitos);
        return resultado;
    }
}
